/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Aug 11 16:05:30 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.tyloo.po;

import java.io.Serializable;

import com.tyloo.fw.orm.IdPersistent;

public class Role extends IdPersistent implements
		Serializable {

	private static final long serialVersionUID = 2678594360456567383L;

	private Integer id;

	private String name;

	private int groupPri;

	private String salseType;

	private String memo;

	private java.util.Date timeCreate;

	private java.util.Date timeModified;

	public int getGroupPri() {
		return groupPri;
	}

	public void setGroupPri(int groupPri) {
		this.groupPri = groupPri;
	}

	@Override
	public Integer getId() {
		return id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSalseType() {
		return salseType;
	}

	public void setSalseType(String salseType) {
		this.salseType = salseType;
	}

	@Override
	public java.util.Date getTimeCreate() {
		return timeCreate;
	}

	@Override
	public void setTimeCreate(java.util.Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Override
	public java.util.Date getTimeModified() {
		return timeModified;
	}

	@Override
	public void setTimeModified(java.util.Date timeModified) {
		this.timeModified = timeModified;
	}

}
